/*
 * Copyright 2024 the original author or authors.
 * <p>
 * Licensed under the Moderne Source Available License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * https://docs.moderne.io/licensing/moderne-source-available-license
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.openrewrite.java.migrate;

import org.junit.jupiter.api.Test;
import org.openrewrite.DocumentExample;
import org.openrewrite.Issue;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.mavenProject;
import static org.openrewrite.maven.Assertions.pomXml;

class AddMockitoJavaAgentToMavenSurefirePluginTest implements RewriteTest {

  @Override
  public void defaults(RecipeSpec spec) {
    spec.recipe(new AddMockitoJavaAgentToMavenSurefirePlugin());
  }

    @DocumentExample
    @Test
    void addsMockitoAgentArgAndPropertiesGoalToMavenPlugins() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsByteBuddyAgentArgWithSurefirePluginAndNoExistingConfigurationWithOlderMockitoVersion() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.3.13</version>
                <relativePath/>
              </parent>
              <properties>
                <argLine>custom value</argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.3.13</version>
                <relativePath/>
              </parent>
              <properties>
                <argLine>custom value</argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>@{argLine} -javaagent:${net.bytebuddy:byte-buddy-agent:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsMockitoAgentArgToExistingConfigurationWithNoArgLineTag() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>
              <properties>
                <customProperty>some-property</customProperty>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <systemPropertyVariables>
                        <propertyName>foobar</propertyName>
                      </systemPropertyVariables>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>
              <properties>
                <customProperty>some-property</customProperty>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <systemPropertyVariables>
                        <propertyName>foobar</propertyName>
                      </systemPropertyVariables>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsMockitoAgentArgToExistingArgLineTagWithNoValue() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <argLine />
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsMockitoAgentArgPreservingExistingArgLineArguments() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <systemPropertyVariables>
                        <propertyName>foobar</propertyName>
                      </systemPropertyVariables>
                      <argLine>-Xmx256m</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <systemPropertyVariables>
                        <propertyName>foobar</propertyName>
                      </systemPropertyVariables>
                      <!--suppress MavenModelInspection -->
                      <argLine>-Xmx256m -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void onlyAddsConfigurationToPomWithMockitoInMultiModuleProject() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <modules>
                <module>test-module1</module>
              </modules>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

            </project>
            """,
          spec -> spec.path("pom.xml")
        ),
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          spec -> spec.path("test-module1/pom.xml")
        )
      )
    );
  }

  @Test
  void addsMavenSurefireAndDependencyPluginsWhenAbsent() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsGoalsTagWithPropertiesGoalToExistingMavenDependencyPluginWhenMissing() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsPropertiesGoalToExistingGoalsSectionInMavenDependencyPlugin() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                        <goals>
                          <goal>analyize</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <configuration>
                          <foobar />
                        </configuration>
                        <goals>
                          <goal>analyize</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Issue("https://github.com/moderneinc/customer-requests/issues/2968")
  @Test
  void addsSeparateExecutionWhenExistingExecutionRunsAfterTests() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsSeparateExecutionWhenPropertiesGoalIsBoundToAPhase() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsSingleExecutionWhenMavenDependencyPluginHasSeveralExecutions() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>unpack</id>
                        <phase>prepare-package</phase>
                        <goals>
                          <goal>unpack-dependencies</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                          <goal>copy-dependencies</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>unpack</id>
                        <phase>prepare-package</phase>
                        <goals>
                          <goal>unpack-dependencies</goal>
                        </goals>
                      </execution>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void makesNoChangeWhenMockitoAgentFlagAlreadyExists() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                      <systemPropertyVariables>
                        <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                      </systemPropertyVariables>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void makesNoChangeWhenMockitoAgentFlagAlreadyExistsUsingSingleLineArgline() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>
              <properties>
                <argLine/>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                      <systemPropertyVariables>
                        <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                      </systemPropertyVariables>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void makesNoChangeWhenMockitoCoreDependencyIsNotOnClasspath() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <systemPropertyVariables>
                        <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                      </systemPropertyVariables>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void makesNoChangesWhenParentPomManagesSurefirePluginAndHasAgentConfiguration() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <modules>
                <module>test-module1</module>
              </modules>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <build>
                <pluginManagement>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                          <!--suppress MavenModelInspection -->
                          <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                          <systemPropertyVariables>
                            <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                          </systemPropertyVariables>
                        </configuration>
                      </plugin>
                  </plugins>
                </pluginManagement>
              </build>
            </project>
            """,
          spec -> spec.path("pom.xml")
        ),
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          spec -> spec.path("test-module1/pom.xml")
        )
      )
    );
  }

  @Test
  void updatesIndividualPomsWhenParentPomManagesSurefirePluginWithoutAgentConfiguration() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <modules>
                <module>test-module1</module>
              </modules>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <build>
                <pluginManagement>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-dependency-plugin</artifactId>
                      <executions>
                        <execution>
                          <id>get-mockito-agent-path</id>
                          <goals>
                            <goal>properties</goal>
                          </goals>
                        </execution>
                      </executions>
                    </plugin>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                          <systemPropertyVariables>
                            <jacoco-agent.destfile>${project.build.directory}/jacoco.exec</jacoco-agent.destfile>
                          </systemPropertyVariables>
                        </configuration>
                      </plugin>
                  </plugins>
                </pluginManagement>
              </build>
            </project>
            """,
          spec -> spec.path("pom.xml")
        ),
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          spec -> spec.path("test-module1/pom.xml")
        )
      )
    );
  }

  @Test
  void makesNoChangesWhenParentPomDeclaresSurefirePluginWithAgentConfiguration() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <packaging>pom</packaging>

              <modules>
                <module>test-module1</module>
              </modules>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-Xmx204m -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          spec -> spec.path("pom.xml")
        ),
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>1.0</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>
            </project>
            """,
          spec -> spec.path("test-module1/pom.xml")
        )
      )
    );
  }

  @Test
  void makesNoChangesWhenAgentConfiguredOnPluginsWithImpliedGroupId() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-Xmx204m -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void augmentsSurefirePluginDeclaredInPluginManagement() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                </plugins>
                <pluginManagement>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                    </plugin>
                  </plugins>
                </pluginManagement>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>${revision}</version>

              <parent>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>3.5.4</version>
                <relativePath/>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.springframework.boot</groupId>
                  <artifactId>spring-boot-starter-test</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                </plugins>
                <pluginManagement>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <configuration>
                        <!--suppress MavenModelInspection -->
                        <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                      </configuration>
                    </plugin>
                  </plugins>
                </pluginManagement>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void addsSurefireAgentToModuleWhenParentReactorPomManagesPluginsWithoutDeclaringThem() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <packaging>pom</packaging>

              <modules>
                <module>test-module1</module>
              </modules>

              <dependencyManagement>
                <dependencies>
                  <dependency>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-core</artifactId>
                    <version>5.14.0</version>
                    <scope>test</scope>
                  </dependency>
                </dependencies>
              </dependencyManagement>

              <build>
                <pluginManagement>
                  <plugins>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-dependency-plugin</artifactId>
                      <version>3.11.0</version>
                    </plugin>
                    <plugin>
                      <groupId>org.apache.maven.plugins</groupId>
                      <artifactId>maven-surefire-plugin</artifactId>
                      <version>3.5.6</version>
                    </plugin>
                  </plugins>
                </pluginManagement>
              </build>
            </project>
            """,
          spec -> spec.path("pom.xml")
        ),
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>1.0</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test-module1</artifactId>
              <version>1.0</version>

              <parent>
                <groupId>org.sample</groupId>
                <artifactId>test</artifactId>
                <version>1.0</version>
                <relativePath>../pom.xml</relativePath>
              </parent>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          spec -> spec.path("test-module1/pom.xml")
        )
      )
    );
  }

  @Test
  void omitsLateArgLineReplacementWhenNothingSetsArgLineAtRuntime() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>-javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void usesLateArgLineReplacementWhenJacocoPluginPresent() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.12</version>
                  </plugin>
                </plugins>
              </build>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <properties>
                <argLine></argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.12</version>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void usesLateArgLineReplacementWhenJacocoPluginOnlyActiveInProfile() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <profiles>
                <profile>
                  <id>coverage</id>
                  <build>
                    <plugins>
                      <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.12</version>
                      </plugin>
                    </plugins>
                  </build>
                </profile>
              </profiles>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <properties>
                <argLine></argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <profiles>
                <profile>
                  <id>coverage</id>
                  <build>
                    <plugins>
                      <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.12</version>
                      </plugin>
                    </plugins>
                  </build>
                </profile>
              </profiles>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }

  @Test
  void usesLateArgLineReplacementWhenArgLinePropertyAlreadyDeclared() {
    rewriteRun(
      mavenProject("test-project",
        pomXml(
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <properties>
                <argLine>-Xmx512m</argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """,
          """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>org.sample</groupId>
              <artifactId>test</artifactId>
              <version>1.0</version>
              <properties>
                <argLine>-Xmx512m</argLine>
              </properties>

              <dependencies>
                <dependency>
                  <groupId>org.mockito</groupId>
                  <artifactId>mockito-core</artifactId>
                  <version>5.17.0</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                      <execution>
                        <id>get-mockito-agent-path</id>
                        <goals>
                          <goal>properties</goal>
                        </goals>
                      </execution>
                    </executions>
                  </plugin>
                  <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <!--suppress MavenModelInspection -->
                      <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </project>
            """
        )
      )
    );
  }
}
