package org.openrewrite.java.migrate.jakarta;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.openrewrite.config.Environment;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;
import static org.openrewrite.maven.Assertions.pomXml;

public class JacksonJavaxtoJakartaTest implements RewriteTest {

    public void defaults(RecipeSpec spec) {
        spec.recipe(
          Environment.builder()
            .scanRuntimeClasspath("org.openrewrite.java.migrate")
            .build()
            .activateRecipes("org.openrewrite.java.migrate.jakarta.JacksonJavaxToJakarta")
        );
    }

    @Test
    void migrateJacksonDependencies() {
        rewriteRun(
          pomXml(
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.fasterxml.jackson.module</groupId>
                            <artifactId>jackson-module-jaxb-annotations</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-cbor-provider</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-json-provider</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-smile-provider</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-xml-provider</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-yaml-provider</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.datatype</groupId>
                            <artifactId>jackson-datatype-jsr353</artifactId>
                            <version>2.12.1</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish</groupId>
                            <artifactId>javax.json</artifactId>
                            <version>1.1.4</version>
                        </dependency>
                    </dependencies>
                </project>
            """,
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.fasterxml.jackson.module</groupId>
                            <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                            <artifactId>jackson-jakarta-rs-cbor-provider</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                            <artifactId>jackson-jakarta-rs-json-provider</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                            <artifactId>jackson-jakarta-rs-smile-provider</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                            <artifactId>jackson-jakarta-rs-xml-provider</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                            <artifactId>jackson-jakarta-rs-yaml-provider</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.datatype</groupId>
                            <artifactId>jackson-datatype-jakarta-jsonp</artifactId>
                            <version>2.13.4</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish</groupId>
                            <artifactId>jakarta.json</artifactId>
                            <version>2.0.1</version>
                        </dependency>
                    </dependencies>
                </project>
            """
          )
        );
    }

    @Test
    @Disabled("Disabled until ChangeManagedDependencyGroupAndArtifactId supports dynamic versions")
    void migrateJacksonManagedDependencies() {
        rewriteRun(
          pomXml(
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>com.fasterxml.jackson.module</groupId>
                                <artifactId>jackson-module-jaxb-annotations</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                                <artifactId>jackson-jaxrs-cbor-provider</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                                <artifactId>jackson-jaxrs-json-provider</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                                <artifactId>jackson-jaxrs-smile-provider</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                                <artifactId>jackson-jaxrs-xml-provider</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jaxrs</groupId>
                                <artifactId>jackson-jaxrs-yaml-provider</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.datatype</groupId>
                                <artifactId>jackson-datatype-jsr353</artifactId>
                                <version>2.12.1</version>
                            </dependency>
                            <dependency>
                                <groupId>org.glassfish</groupId>
                                <artifactId>javax.json</artifactId>
                                <version>1.1.4</version>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                </project>
            """,
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <dependencyManagement>
                        <dependencies>
                            <dependency>
                                <groupId>com.fasterxml.jackson.module</groupId>
                                <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                                <artifactId>jackson-jakarta-rs-cbor-provider</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                                <artifactId>jackson-jakarta-rs-json-provider</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                                <artifactId>jackson-jakarta-rs-smile-provider</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                                <artifactId>jackson-jakarta-rs-xml-provider</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.jakarta.rs</groupId>
                                <artifactId>jackson-jakarta-rs-yaml-provider</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>com.fasterxml.jackson.datatype</groupId>
                                <artifactId>jackson-datatype-jakarta-jsonp</artifactId>
                                <version>2.13.4</version>
                            </dependency>
                            <dependency>
                                <groupId>org.glassfish</groupId>
                                <artifactId>jakarta.json</artifactId>
                                <version>2.0.1</version>
                            </dependency>
                        </dependencies>
                    </dependencyManagement>
                </project>
            """
          )
        );
    }

    @Test
    @Disabled("Disabled until ChangeDependencyGroupAndArtifactId follows property placeholders")
    void migrateJacksonDependenciesWithVersionProperty() {
        rewriteRun(
          pomXml(
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <properties>
                        <jackson.version>2.12.1</jackson.version>
                        <glassfish.version>1.1.4</glassfish.version>
                    </properties>
                    <dependencies>
                        <dependency>
                            <groupId>com.fasterxml.jackson.module</groupId>
                            <artifactId>jackson-module-jaxb-annotations</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-cbor-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-json-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-smile-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-xml-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-yaml-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.datatype</groupId>
                            <artifactId>jackson-datatype-jsr353</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish</groupId>
                            <artifactId>javax.json</artifactId>
                            <version>${glassfish.version}</version>
                        </dependency>
                    </dependencies>
                </project>
            """,
            """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.jackson</groupId>
                    <artifactId>jackson-legacy</artifactId>
                    <version>1.0.0</version>
                    <properties>
                        <jackson.version>2.13.4</jackson.version>
                        <glassfish.version>2.0.1</glassfish.version>
                    </properties>
                    <dependencies>
                        <dependency>
                            <groupId>com.fasterxml.jackson.module</groupId>
                            <artifactId>jackson-module-jaxb-annotations</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-cbor-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-json-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-smile-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-xml-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.jaxrs</groupId>
                            <artifactId>jackson-jaxrs-yaml-provider</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>com.fasterxml.jackson.datatype</groupId>
                            <artifactId>jackson-datatype-jsr353</artifactId>
                            <version>${jackson.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.glassfish</groupId>
                            <artifactId>javax.json</artifactId>
                            <version>${glassfish.version}</version>
                        </dependency>
                    </dependencies>
                </project>
            """
          )
        );
    }
}
