---
name: dependency-check

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 18 * * *

concurrency:
  group: dependency-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-check:
    uses: openrewrite/gh-automation/.github/workflows/dependency-check-gradle.yml@main
    secrets:
      slack_alerts_webhook: ${{ secrets.SLACK_ALERTS_WEBHOOK }}
      gradle_enterprise_access_key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      gradle_enterprise_cache_username: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
      gradle_enterprise_cache_password: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
